services:
  php-apache:
    container_name: "${CONTAINER_NAME_PREFIX}-apache-php"
    build: .
    volumes:
      - ${PATH_TO_LARAVEL_PROJECT}:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db

  db:
    container_name: "${CONTAINER_NAME_PREFIX}-mysql"
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    container_name: "${CONTAINER_NAME_PREFIX}-adminer"
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"
volumes:
  db: